# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'reservation_page.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 515)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(49, 19, 591, 231))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.roomNo_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.roomNo_label.setObjectName("roomNo_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.roomNo_label)
        self.guistName_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.guistName_label.setObjectName("guistName_label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.guistName_label)
        self.checkIn_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.checkIn_label.setObjectName("checkIn_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.checkIn_label)
        self.guistId_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.guistId_label.setObjectName("guistId_label")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.guistId_label)
        self.roomNo = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.roomNo.setText("")
        self.roomNo.setPlaceholderText("")
        self.roomNo.setObjectName("roomNo")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.roomNo)
        self.guistName = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.guistName.setText("")
        self.guistName.setObjectName("guistName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.guistName)
        self.checkIn = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.checkIn.setObjectName("checkIn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkIn)
        self.checkOut = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.checkOut.setObjectName("checkOut")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.checkOut)
        self.guistId = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.guistId.setObjectName("guistId")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.guistId)
        self.checkOut_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.checkOut_label.setObjectName("checkOut_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkOut_label)
        self.price_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.price_label.setObjectName("price_label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.price_label)
        self.price = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.price.setInputMask("")
        self.price.setText("")
        self.price.setObjectName("price")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.price)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(190, 370, 331, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.makeReservation = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.makeReservation.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.makeReservation.setObjectName("makeReservation")
        self.horizontalLayout.addWidget(self.makeReservation)
        self.cancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.cancel.setObjectName("cancel")
        self.horizontalLayout.addWidget(self.cancel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionCAlender = QtWidgets.QAction(MainWindow)
        self.actionCAlender.setObjectName("actionCAlender")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionCAlender)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.roomNo_label.setText(_translate("MainWindow", "Room No."))
        self.guistName_label.setText(_translate("MainWindow", "Guist Name"))
        self.checkIn_label.setText(_translate("MainWindow", "Check In"))
        self.guistId_label.setText(_translate("MainWindow", "Guist ID"))
        self.checkOut_label.setText(_translate("MainWindow", "Check Out"))
        self.price_label.setText(_translate("MainWindow", "Price"))
        self.makeReservation.setText(_translate("MainWindow", "Make Reservation"))
        self.cancel.setText(_translate("MainWindow", "Cancel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Make Reservation"))
        self.actionCAlender.setText(_translate("MainWindow", "Reserved Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
